server:
  name: beta
  port: 10001
dataSource:
  host: 127.0.0.1
  port: 3306
  maxPoolSize: 30
  user: root
  password: aggaer520
  database: imooc
  connectTimeout: 10000
  queryTimeout: 8000
  maxConnectionRetries: 3
  connectionRetryDelay: 3000
  cachePreparedStatements: true
