server:
  name: beta
  port: 10001
dataSource:
  host: 192.168.32.191
  port: 3306
  maxPoolSize: 30
  user: ptlppz
  password: '123456'
  database: pintuan
  connectTimeout: 10000
  queryTimeout: 8000
  maxConnectionRetries: 3
  connectionRetryDelay: 3000
  cachePreparedStatements: true
